/**
 * Natural Language Strategy Builder — shared types.
 *
 * A ParsedStrategy is a small, closed-vocabulary filter spec — never
 * arbitrary code or a raw query string generated by the LLM. Every metric,
 * operator, and value the model can produce is drawn from a fixed enum
 * (see StrategyMetric/StrategyOperator below) and re-validated server-side
 * (lib/strategy/parse.ts's sanitizeParsedStrategy) before ever being
 * executed — the model's job is translation (English/Hebrew free text ->
 * this structured shape), never code generation or direct data access.
 */

/**
 * Every metric a strategy filter/sort can reference. Deliberately only
 * things the execution engine (lib/strategy/execute.ts) can actually
 * compute for the whole screening universe in one run:
 *  - price/changePercent/marketCap/peRatio/dividendYieldPercent/volume:
 *    straight from a batched live quote (getStrategyQuotes in yahoo.ts).
 *  - rsi14/priceVsSma50/priceVsSma200: computed from daily price history
 *    (lib/finance/indicators.ts), only fetched for symbols that already
 *    passed every quote-based filter — see execute.ts's two-stage design.
 */
export const STRATEGY_METRICS = [
  "price",
  "changePercent",
  "marketCap",
  "peRatio",
  "dividendYieldPercent",
  "volume",
  "rsi14",
  "priceVsSma50",
  "priceVsSma200",
] as const;
export type StrategyMetric = (typeof STRATEGY_METRICS)[number];

export const STRATEGY_OPERATORS = ["gt", "gte", "lt", "lte", "eq"] as const;
export type StrategyOperator = (typeof STRATEGY_OPERATORS)[number];

export interface StrategyFilter {
  metric: StrategyMetric;
  operator: StrategyOperator;
  value: number;
}

export interface ParsedStrategy {
  filters: StrategyFilter[];
  sortBy: StrategyMetric | null;
  sortDirection: "asc" | "desc" | null;
  /** e.g. "top 10 by market cap" -> limit: 10. Null means "no explicit limit requested". */
  limit: number | null;
  /**
   * Plain-language restatement of what was understood, in the SAME
   * language the user wrote in (English or Hebrew) — this is what the UI
   * shows in the "generated filtering logic" transparency panel above the
   * raw filter list, since "rsi14 lt 30" means a lot less to most users
   * than "RSI below 30 (oversold)".
   */
  explanation: string;
  /**
   * True when the model could not confidently map the input to any
   * supported filter at all (e.g. a request for data this app doesn't
   * have, like short interest, or genuinely not a screening strategy) —
   * the UI shows `explanation` as an error/clarification message instead
   * of running an empty screen.
   */
  unsupported: boolean;
}

export interface StrategyResultRow {
  symbol: string;
  name: string;
  price: number | null;
  changePercent: number | null;
  marketCap: number | null;
  peRatio: number | null;
  dividendYieldPercent: number | null;
  volume: number | null;
  rsi14: number | null;
  priceVsSma50: number | null;
  priceVsSma200: number | null;
}

export interface StrategyRunResult {
  parsed: ParsedStrategy;
  results: StrategyResultRow[];
  /** Total symbols in the screening universe this run considered — see STRATEGY_UNIVERSE_SYMBOLS's doc comment for why this is a bounded, curated list rather than the whole market. */
  universeSize: number;
}
